version: '3.8'

services:
  api:
    environment:
      - DJANGO_DEBUG=1
    volumes:
      - ./:/app
    command: >
      sh -c "while ! pg_isready -h db -p 5432; do sleep 1; done;
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
